### ISSUE TITLE
error when opening temp image

### ISSUE THREAD

**Issue by SlimeQ** [Coyote-A/ultimate-upscale-for-automatic1111#115]
![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/3934698/4525c145-27fd-4182-83cd-bc1ef453b3e1)

```
100%|████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:01<00:00,  5.88it/s]
Total progress:  65%|████████████████████████████████████████▏                     | 1400/2160 [06:06<03:19,  3.82it/s]
Traceback (most recent call last):███████████████████████████▏                     | 1400/2160 [06:06<02:17,  5.53it/s]
  File "C:\Users\username\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\username\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\username\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "C:\Users\username\stable-diffusion-webui-1.4.0\venv\lib\site-packages\gradio\components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "C:\Users\username\stable-diffusion-webui-1.4.0\modules\ui_tempdir.py", line 55, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 549, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\tempfile.py", line 252, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\AppData\\Local\\Temp\\gradio\\tmpwk21hl92.png
```

Upon further inspection, the `gradio` directory does not exist. I'm running auto1111 out of my home directory `C:\\Users\\username\stable-diffusion-webui`

**Comment by SlimeQ** [comment]
(creating the gradio directory manually fixed this problem)
