### ISSUE TITLE
Error completing request since latest update

### ISSUE THREAD

**Issue by JGM-89** [Coyote-A/ultimate-upscale-for-automatic1111#118]
*** Error completing request
*** Arguments: ('task(fif4d5lssy3tvlr)', 0, 'sharp details', '', [], <PIL.Image.Image image mode=RGBA size=1456x816 at 0x201E58EE4A0>, None, None, None, None, None, None, 20, 16, 4, 0, 1, False, False, 1, 1, 27.5, 1.5, 0.08, -1.0, -1.0, 0, 0, 0, False, 1, 512, 512, 4, 0, 0, 32, 0, '', '', '', [], 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "C:\Users\user\Documents\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\user\Documents\automatic1111\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Users\user\Documents\automatic1111\stable-diffusion-webui\modules\img2img.py", line 196, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "C:\Users\user\Documents\automatic1111\stable-diffusion-webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 18 required positional arguments: '_', 'tile_width', 'tile_height', 'mask_blur', 'padding', 'seams_fix_width', 'seams_fix_denoise', 'seams_fix_padding', 'upscaler_index', 'save_upscaled_image', 'redraw_mode', 'save_seams_fix_image', 'seams_fix_mask_blur', 'seams_fix_type', 'target_size_type', 'custom_width', 'custom_height', and 'custom_scale'

---

**Comment by Phxlnk1** [comment]
From another thread

> > same issue at web UI 1.4 version: [v1.4.0]•  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [a77aa87aa3]
> 
> When I removed sd-webui-mov2mov, ultimate-upscale-for-automatic1111 is work.
