### ISSUE TITLE
AssertionError: extension access disabled because of command line flags (doesn't install)

### ISSUE THREAD

**Issue by turian** [Coyote-A/ultimate-upscale-for-automatic1111#18]
When you try to install on rundiffusion.com's AUTO1111, you get this error:

```
AssertionError: extension access disabled because of command line flags
[object Object]
```

**Comment by turian** [comment]
I also get this error when installing on a local GPU:

```
Arguments: ('https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git', ['ads', 'localization', 'installed'], 0) {}
Traceback (most recent call last):
  File "/home/joseph/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/joseph/stable-diffusion-webui/modules/ui_extensions.py", line 166, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/home/joseph/stable-diffusion-webui/modules/ui_extensions.py", line 119, in install_extension_from_url
    check_access()
  File "/home/joseph/stable-diffusion-webui/modules/ui_extensions.py", line 22, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```

**Comment by MrFelt** [comment]
If you are using --listen as a launch option, extension tab is disabled for obvious reasons.
