### ISSUE TITLE
AttributeError: module 'modules.images' has no attribute 'flatten'

### ISSUE THREAD

**Issue by coltography** [Coyote-A/ultimate-upscale-for-automatic1111#19]
First attempt at this and I'm getting error: `AttributeError: module 'modules.images' has no attribute 'flatten'`

Below that it says: `Time taken: 0.03s Torch active/reserved: 0/0 MiB, Sys VRAM: 2478/12288 MiB (20.17%)`

Not experienced with troubleshooting auto111 or the extensions so if there's a way to provide additional info please let me know.

Edit: this is the output in the cmd line window:

```Error completing request
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=1600x896 at 0x22CB2FB6B90>, None, None, None, None, 0, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 1, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\Users\Colton\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Colton\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\Users\Colton\stable-diffusion-webui-master\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\Users\Colton\stable-diffusion-webui-master\modules\scripts.py", line 328, in run
    processed = script.run(p, *script_args)
  File "C:\Users\Colton\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 524, in run
    init_img = images.flatten(init_img, opts.img2img_background_color)
AttributeError: module 'modules.images' has no attribute 'flatten'```

**Comment by DionysosD** [comment]
I'm having the exact same Problem.

**Comment by coltography** [comment]
> 

Update your auto1111 and it will fix it.

**Comment by coltography** [comment]
Updating my automatic1111 fixed this. Just git pull and it'll work. 

Closing
