### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by sx2astra** [Coyote-A/ultimate-upscale-for-automatic1111#24]
Have not been able to get this script to work at all. Everything I try with whatever settings I try to get work fails with this error. Have the most up to date version of the webui.

```
Traceback (most recent call last):
  File "D:\Git\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Git\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Git\stable-diffusion-webui\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\Git\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "D:\Git\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 543, in run
    upscaler.process()
  File "D:\Git\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 129, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
  File "D:\Git\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 238, in start
    return self.chess_process(p, image, rows, cols)
  File "D:\Git\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 208, in chess_process
    processed = processing.process_images(p)
  File "D:\Git\stable-diffusion-webui\modules\processing.py", line 476, in process_images
    res = process_images_inner(p)
  File "D:\Git\stable-diffusion-webui\modules\processing.py", line 654, in process_images_inner
    image = apply_overlay(image, p.paste_to, i, p.overlay_images)
  File "D:\Git\stable-diffusion-webui\modules\processing.py", line 68, in apply_overlay
    image = images.resize_image(1, image, w, h)
  File "D:\Git\stable-diffusion-webui\modules\images.py", line 278, in resize_image
    resized = resize(im, src_w, src_h)
  File "D:\Git\stable-diffusion-webui\modules\images.py", line 261, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "D:\Git\stable-diffusion-webui\modules\upscaler.py", line 64, in upscale
    img = self.do_upscale(img, selected_model)
  File "D:\Git\stable-diffusion-webui\modules\esrgan_model.py", line 154, in do_upscale
    img = esrgan_upscale(model, img)
  File "D:\Git\stable-diffusion-webui\modules\esrgan_model.py", line 225, in esrgan_upscale
    output = upscale_without_tiling(model, tile)
  File "D:\Git\stable-diffusion-webui\modules\esrgan_model.py", line 204, in upscale_without_tiling
    output = model(img)
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Git\stable-diffusion-webui\modules\esrgan_model_arch.py", line 61, in forward
    return self.model(feat)
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Git\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 174, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Git\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead
```

**Comment by vladlearns** [comment]
try workaround from this issue https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/issues/3

**Comment by sx2astra** [comment]
> try workaround from this issue #3

Haha, guess I should have looked through the closed items as well. Thanks man though this should be in the guide somewhere imo.
