### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Rogal80** [Coyote-A/ultimate-upscale-for-automatic1111#25]
Hi, after new update of A1111 this issue appear :

Traceback (most recent call last):
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\scripts.py", line 347, in run
    processed = script.run(p, *script_args)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 543, in run
    upscaler.process()
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 129, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 236, in start
    return self.linear_process(p, image, rows, cols)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 171, in linear_process
    processed = processing.process_images(p)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 485, in process_images
    res = process_images_inner(p)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 667, in process_images_inner
    image = apply_overlay(image, p.paste_to, i, p.overlay_images)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 68, in apply_overlay
    image = images.resize_image(1, image, w, h)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\images.py", line 278, in resize_image
    resized = resize(im, src_w, src_h)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\images.py", line 261, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\upscaler.py", line 64, in upscale
    img = self.do_upscale(img, selected_model)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 154, in do_upscale
    img = esrgan_upscale(model, img)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 225, in esrgan_upscale
    output = upscale_without_tiling(model, tile)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 204, in upscale_without_tiling
    output = model(img)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model_arch.py", line 61, in forward
    return self.model(feat)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 256, 256] to have 3 channels, but got 4 channels instead

Windows 
Firefox
Commit hash: 6cff4401824299a983c8e13424018efc347b4a2b

**Comment by Jopezzia** [comment]
Hi! Try fix from #3

**Comment by Rogal80** [comment]
fixed :) thx
