### ISSUE TITLE
It is not possible to output both Upscaled and Seams fix at the same time using SwinIR 4x.

### ISSUE THREAD

**Issue by sus00236** [Coyote-A/ultimate-upscale-for-automatic1111#27]
I found that when using SwinIR, if I try to output both the Upscaled and Seams fix images at the same time, the following error occurs and only the Upscaled image is output. Is this a bug? Because I am using LSDR as the upscaler and I don't have this problem.
```
Error completing request39:13,  3.75it/s]
Arguments: ('task(q71xh4bp1dd9w7q)', 0, 'highest quality,masterpiece,hand of Guido Daniele,blue_hair, 1girl, (rem_\\(re:zero\\)),solo,maid, short_hair, detached_sleeves, roswaal_mansion_maid_uniform, white_legwear, skirt,beautiful sunset,falling petals,upper body,85mm lens,8K,HD,(family friendly),Smile,CG,outside roswaal_mansion,x hairpin,welcome,(pink lips),beautiful ribbon,bangs cover the right eye,,water blue eyes,(holding a super cute bird:1.25),', 'nsfw,ugly,bad_anatomy,bad_hands,extra_hands,missing_fingers,broken hand,(more than two hands),well proportioned hands,more than two legs,unclear eyes,pull skirt,missing_arms,mutilated,extra limbs,extra legs,cloned face,fused fingers,extra_digit, fewer_digits,extra_digits,jpeg_artifacts,signature,watermark,username,blurry,large_breasts,worst_quality,low_quality,normal_quality,mirror image, Vague,unclear fingers,bad hands', [], <PIL.Image.Image image mode=RGBA size=1536x2048 at 0x25E400AF5B0>, None, None, None, None, None, None, 70, 0, 4, 0, 1, False, False, 1, 1, 12, 0.4, -1.0, -1.0, 0, 0, 0, False, 2048, 1536, 0, 0, 32, 0, '', '', '', [], 10, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, None, '', 0.2, 0.1, 1, 1, False, True, True, False, False, False, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 8, 32, 64, 0.35, 32, 8, False, 0, True, 8, 1, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\Users\sus00\Desktop\AI\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\sus00\Desktop\AI\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\sus00\Desktop\AI\modules\img2img.py", line 166, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\Users\sus00\Desktop\AI\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "C:\Users\sus00\Desktop\AI\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 543, in run
    upscaler.process()
  File "C:\Users\sus00\Desktop\AI\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 136, in process
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)
  File "C:\Users\sus00\Desktop\AI\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 401, in start
    return self.band_pass_process(p, image, rows, cols)
  File "C:\Users\sus00\Desktop\AI\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 373, in band_pass_process
    processed = processing.process_images(p)
  File "C:\Users\sus00\Desktop\AI\modules\processing.py", line 484, in process_images
    res = process_images_inner(p)
  File "C:\Users\sus00\Desktop\AI\modules\processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\Users\sus00\Desktop\AI\modules\processing.py", line 946, in init
    mask = mask.crop(crop_region)
  File "C:\Users\sus00\Desktop\AI\venv\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'
```

**Comment by sus00236** [comment]
I figured out the reason, it's due to the incorrect image size. It's not a bug
