### ISSUE TITLE
[BUG] UU its broken 

### ISSUE THREAD

**Issue by Rogal80** [Coyote-A/ultimate-upscale-for-automatic1111#3]
Hi, maybe I did something wrong, and I have this issue each time :

Traceback (most recent call last):
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "I:\Github\new_webui\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\img2img.py", line 150, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 492, in run
    upscaler.process()
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 123, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 231, in start
    return self.chess_process(p, image, rows, cols)
  File "I:\Github\new_webui\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 201, in chess_process
    processed = processing.process_images(p)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 645, in process_images_inner
    image = apply_overlay(image, p.paste_to, i, p.overlay_images)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\processing.py", line 68, in apply_overlay
    image = images.resize_image(1, image, w, h)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\images.py", line 278, in resize_image
    resized = resize(im, src_w, src_h)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\images.py", line 261, in resize
    im = upscaler.scaler.upscale(im, scale, upscaler.data_path)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\upscaler.py", line 64, in upscale
    img = self.do_upscale(img, selected_model)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 154, in do_upscale
    img = esrgan_upscale(model, img)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 225, in esrgan_upscale
    output = upscale_without_tiling(model, tile)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model.py", line 204, in upscale_without_tiling
    output = model(img)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\modules\esrgan_model_arch.py", line 61, in forward
    return self.model(feat)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "I:\Github\new_webui\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead

**Comment by Coyote-A** [comment]
Hi, can you share more info about input parameters?
Also try to set upscaler for img2img to none
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/11600962/211805882-3f1334b8-18f1-4fd5-ab2c-27bd9d552ffd.png">
