### ISSUE TITLE
Bug Report / AttributeError: 'USDUSeamsFix' object has no attribute '_width'  /  ValueError: Coordinate 'right' is less than 'left'

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Coyote-A/ultimate-upscale-for-automatic1111#5]
When I'm upscaling a 4k picture to 8k everything works as it should. 

When I'm trying to upscale the same 4k picture to 8k but with "**seams fix**" it runs for a long time but then it fails at near the end (over 80% completed but I do not have an exact number).

On the A1111 WebUI the error message printed is: `AttributeError: 'USDUSeamsFix' object has no attribute '_width'`
I get the same error whether or not I check the "**Seams Fix**" checkbox in the save options at the very bottom. 

This happens with the seams fix type set to "**Band Pass**". 
This **does NOT happen** when the seams fix type is set to "**Half-Tile offset pass**".

My guess is there is an extra underscore just before "**width**" on line 356 of `ultimate-upscale.py` as there is no "**_width**" anywhere else in the code, but plenty of "**width**". I will try to modify the code by changing line 356 from
 `p.width = self._width + self.padding * 2` into  `p.width = self.width + self.padding * 2` and I'll check if it fixes the problem. And of course I'll come back here to report. If this works locally, I will try my first ever pull request (I have no idea what I'm doing !!!).

The detailed log from the WebUI command window is:
```
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGBA size=4096x2048 at 0x25B6AF9FCD0>, None, None, None, None, None, None, 30, 15, 4, 0, 1, False, False, 1, 1, 7, 0.35, -1.0, -1.0, 0, 0, 0, False, 768, 768, 3, 0, 32, 0, '', '', 18, 0, 0, 0, 0, 0.25, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, True, False, 0, -1, True, '<p style="margin-bottom:0.75em">You can edit extensions/model-keyword/model-keyword-user.txt to add custom mappings</p>', 'keyword prompt', 'keyword1, keyword2', True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, False, False, False, False, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'Refresh models', False, 'Denoised', 5.0, 0.0, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, False, 'C:\\stable-diffusion-webui-master\\extensions\\sd-webui-riffusion\\outputs', 'Refresh Inline Audio (Last Batch)', None, None, None, None, None, None, None, None, False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, '', False, False, False, False, 'Auto', 0.5, 1, 0, 0, 384, 384, False, False, True, True, True, False, True, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, '{inspiration}', None, 0, 1, 384, 384, True, False, True, True, True, False, 1, True, 3, False, 3, False, 3, 1, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 768, 20, 55, 64, 0.35, 32, 7, True, 0, True, 8, 1, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-master\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 533, in run
    upscaler.process()
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 134, in process
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 392, in start
    return self.band_pass_process(p, image, rows, cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 356, in band_pass_process
    p.width = self._width + self.padding * 2
AttributeError: 'USDUSeamsFix' object has no attribute '_width'
```

**Comment by AugmentedRealityCat** [comment]
Ok, the fix works as I was able to get further in the process and trigger another bug.
I created a fork and made a pull request with the fix, which I then merged with my fork. I hope I got this right - this is my first !
Here is the link in case this is useful for anyone besides me:
https://github.com/AugmentedRealityCat/ultimate-upscale-for-automatic1111

Here is the error message:
`ValueError: Coordinate 'right' is less than 'left'`

Here is the log from the WebUI Command Window:

```
Error completing request
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGBA size=4096x2048 at 0x18C335D0940>, None, None, None, None, None, None, 30, 15, 4, 0, 1, False, False, 1, 1, 7, 0.35, -1.0, -1.0, 0, 0, 0, False, 768, 768, 3, 0, 32, 0, '', '', 18, 0, 0, 0, 0, 0.25, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, True, False, 0, -1, True, '<p style="margin-bottom:0.75em">You can edit extensions/model-keyword/model-keyword-user.txt to add custom mappings</p>', 'keyword prompt', 'keyword1, keyword2', True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, False, False, False, False, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'Refresh models', False, 'Denoised', 5.0, 0.0, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, False, 'C:\\stable-diffusion-webui-master\\extensions\\sd-webui-riffusion\\outputs', 'Refresh Inline Audio (Last Batch)', None, None, None, None, None, None, None, None, False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, '', False, False, False, False, 'Auto', 0.5, 1, 0, 0, 384, 384, False, False, True, True, True, False, True, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, '{inspiration}', None, 0, 1, 384, 384, True, False, True, True, True, False, 1, True, 3, False, 3, False, 3, 1, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 768, 20, 55, 64, 0.35, 32, 7, True, 0, True, 8, 1, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-master\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 533, in run
    upscaler.process()
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 134, in process
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 392, in start
    return self.band_pass_process(p, image, rows, cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 380, in band_pass_process
    processed = processing.process_images(p)
  File "C:\stable-diffusion-webui-master\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui-master\modules\processing.py", line 572, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "C:\stable-diffusion-webui-master\modules\processing.py", line 916, in init
    mask = mask.crop(crop_region)
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'
```

**Comment by nabileisa** [comment]
Hi @Coyote-A , first of all thanks for the amazing extension
I got that same `ValueError: Coordinate 'right' is less than 'left'` with the latest version installed, and I thought a would provide a little info
I was attempting to `scale from image size` by a factor of 2 with Seams fix: `band pass` enabled.
Please note that the dimensions of the original image were not symmetrical `1616*912`
and the tile size was `720` with img2img denoising value of `.5` and everything else was the default.
hope this helps.
here is the complete error:
```
Traceback (most recent call last):
  File "L:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "L:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "L:\stable-diffusion-webui\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "L:\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "L:\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 543, in run
    upscaler.process()
  File "L:\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 136, in process
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)
  File "L:\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 401, in start
    return self.band_pass_process(p, image, rows, cols)
  File "L:\stable-diffusion-webui\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 388, in band_pass_process
    processed = processing.process_images(p)
  File "L:\stable-diffusion-webui\modules\processing.py", line 479, in process_images
    res = process_images_inner(p)
  File "L:\stable-diffusion-webui\modules\processing.py", line 572, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "L:\stable-diffusion-webui\modules\processing.py", line 916, in init
    mask = mask.crop(crop_region)
  File "L:\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 1228, in crop
    raise ValueError(msg)
ValueError: Coordinate 'right' is less than 'left'
```

**Comment by AugmentedRealityCat** [comment]
> hi, i didn't find pr in this repo, so i made changes manually in [d2f9318](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/commit/d2f931808483b88313e51b5866309527b8129808)

The important thing is that you fixed it. 
I'm just beginning to learn how those pull request and commit and branch and forks are working so it's totally normal if I did not do it properly. 

> 
> but i didn't get ValueError: Coordinate 'right' is less than 'left' error. can you please share more information about bug reproduction?

I will try to find more information about that bug and I will share whatever I find over here after.
