### ISSUE TITLE
Bug Report / offset pass + Intersections / UnboundLocalError: local variable 'processed' referenced before assignment

### ISSUE THREAD

**Issue by AugmentedRealityCat** [Coyote-A/ultimate-upscale-for-automatic1111#7]
When using the Fix Seams option and setting the type to `Half-type offset pass + Intersections`, and only for this type, I get this error message near the end of the image synthesis process:
`UnboundLocalError: local variable 'processed' referenced before assignment`

The image result is not shown on the WebUI (just the little error icon from Gradio), but there is one image (and only one) saved on the hard disk. It's probably the upscaled picture in its initial state, before the Seams Fix could be applied. 

Here is the complete log from the Command Window:
```
Error completing request:05,  2.13it/s]
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGBA size=1024x512 at 0x18C336ADBA0>, None, None, None, None, None, None, 30, 15, 4, 0, 1, False, False, 1, 1, 7, 0.35, -1.0, -1.0, 0, 0, 0, False, 768, 768, 3, 0, 32, 0, '', '', 18, 0, 0, 0, 0, 0.25, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, False, 0, -1, True, '<p style="margin-bottom:0.75em">You can edit extensions/model-keyword/model-keyword-user.txt to add custom mappings</p>', 'keyword prompt', 'keyword1, keyword2', True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, False, False, False, False, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'LoRA', 'None', 1, 'Refresh models', False, 'Denoised', 5.0, 0.0, False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False, False, True, False, 'C:\\stable-diffusion-webui-master\\extensions\\sd-webui-riffusion\\outputs', 'Refresh Inline Audio (Last Batch)', None, None, None, None, None, None, None, None, False, 4.0, '', 10.0, False, False, True, 30.0, True, False, False, 0, 0.0, 10.0, True, 30.0, True, '', False, False, False, False, 'Auto', 0.5, 1, 0, 0, 384, 384, False, False, True, True, True, False, True, 1, False, False, 2.5, 4, 0, False, 0, 1, False, False, 'u2net', False, False, False, '{inspiration}', None, 0, 1, 384, 384, True, False, True, True, True, False, 1, True, 3, False, 3, False, 3, 1, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 1024, 20, 56, 64, 0.35, 32, 7, True, 0, True, 8, 3, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui-master\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-master\modules\img2img.py", line 146, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 533, in run
    upscaler.process()
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 134, in process
    self.image = self.seams_fix.start(self.p, self.image, self.rows, self.cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 396, in start
    return self.half_tile_process_corners(p, image, rows, cols)
  File "C:\stable-diffusion-webui-master\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py", line 334, in half_tile_process_corners
    self.initial_info = processed.infotext(p, 0)
UnboundLocalError: local variable 'processed' referenced before assignment
```

**Comment by Jopezzia** [comment]
Hi! Did you interrupt process?

**Comment by Coyote-A** [comment]
maybe you set tile size >= target image size?

**Comment by Jopezzia** [comment]
Update and check problem, please

**Comment by AugmentedRealityCat** [comment]
> maybe you set tile size >= target image size?

That's a good clue actually. I will check that and come back with more info.
