### ISSUE TITLE
Getting "IndexError: list index out of range" after webui restart and attempt to use ultimate-upscale-for-automatic1111

### ISSUE THREAD

**Issue by wiwomu** [Coyote-A/ultimate-upscale-for-automatic1111#80]
Hi All,

I tried a few things prior to posting this:

1. checked the issues pool and didn't find the error in question.
2. restarted the webui
3. checked the config.json for invalid upscaler
4. checked ui-config.json for invalid options
(None of the above mitigated the problem.)

Environment:

* Ubuntu/Linux
* Docker Container
* python3.10

Error:

```
Traceback (most recent call last):
  File "/external-stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/external-stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/external-stable-diffusion-webui/modules/img2img.py", line 170, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "/external-stable-diffusion-webui/modules/scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "/external-stable-diffusion-webui/extensions/ultimate-upscale-for-automatic1111/scripts/ultimate-upscale.py", line 548, in run
    upscaler = USDUpscaler(p, init_img, upscaler_index, save_upscaled_image, save_seams_fix_image, tile_width, tile_height)
  File "/external-stable-diffusion-webui/extensions/ultimate-upscale-for-automatic1111/scripts/ultimate-upscale.py", line 28, in __init__
    self.upscaler = shared.sd_upscalers[upscaler_index]
IndexError: list index out of range
```

In the webui I can see UpScaler options available:

```
Redraw options:

Upscaler
None
Lanczos
Nearest
4x-UltraSharp
4xESRGAN
LDSR
```

I had more before, but moved them out of the way. While that changed the listing, it did not change the error. It was working fine just a few hours ago, but now it acts like parameter list isn't getting into that portion of the script.

Anyone have any thoughts?

**Comment by IaVashik** [comment]
Also getting this
